[package]
name = "rogue"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
petgraph = "0.6.4"
crossterm = "0.27.0"
num-rational = "0.4"
strum = "0.25"
strum_macros = "0.25"
rand = "0.8.5"
